clean:
  latex:
    cmd: latexmk -C *.tex
    help: Remove obsolete files in current conda env
  pip:
    cmd: pip freeze --exclude-editable | xargs pip uninstall -y
    help: uninstall all non-editable pip packages

git:
  ignore-here:
    cmd: echo "*" >> .gitignore
    help: git-ignore all local files

  ignore:
    cmd: |-
      f () {
      if [ -z "$1" ]
        then
          echo "git-ignoring local directory: $(pwd)"
          echo "adding '*' to $(pwd)/.gitignore"
          echo "*" >> .gitignore
        else
          echo "adding to $(pwd)/.gitignore:"
          echo "$@"
          for f in "$@"
          do
            echo "$f" >> .gitignore
          done
      fi
      }
      f
    help: git ignore files [arg] or whole working directory [no arg]
    
   
